### ISSUE TITLE
Generate PDF using pdf engine wkhtmltopdf

### ISSUE THREAD

**Issue by wangkuiyi** [wangkuiyi/pandoc-with-graphviz-filter#2]
However, with the command-line option `--mathjax`, wkhtmltopdf would take forever to complete the rendering.

**Comment by wangkuiyi** [comment]
I found an issue https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1543, however, it seems that wkhtmltopdf stopped upgrading since 2018.

Let me try LaTeX as the pdf engine of pandoc instead.

**Comment by diaohancai** [comment]
Hello~ How to convert html with latex expression to pdf? wkhtmltopdf seems does's work...
